language: python

python:
    - "2.6"
    - "2.7"

install:
    - python setup.py --quiet install

script:
    - python setup.py --quiet test
    - py3kwarn py3kwarn/__init__.py

after_success:
    - pip install --quiet --use-mirrors coveralls
    - coverage run --branch --omit='*/py3kwarn2to3/*,*/site-packages/*,*/distutils/*' setup.py --quiet test
    - coverage report --show-missing
    - coveralls
