language: python

python:
    - "2.6"
    - "2.7"

install:
    - python setup.py --quiet install

script:
    - python setup.py --quiet test
    - py3kwarn2to3 setup.py

after_success:
    - pip install --quiet coveralls
    - coverage run --branch --omit='*/py3kwarn2to3/*,*/site-packages/*,*/distutils/*' setup.py --quiet test
    - coverage run --branch --append --module=py3kwarn.run setup.py
    - coverage report --show-missing
    - coveralls
