language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py --quiet install

script:
    - python setup.py --quiet test
    - nosetests -w py3kwarn2to3/tests

    # Run smoke tests.
    - py3kwarn example.py | grep --quiet 'FixExcept'
    - echo '{}.has_key(3)' | py3kwarn - | grep --quiet 'FixHasKey'
    - echo '3 in {}' | py3kwarn -
    - echo '{}.has_key(3)' | py3kwarn2to3 -

    # Run self tests.
    - py3kwarn py3kwarn setup.py
    - py3kwarn 'py3kwarn2to3/*.py' py3kwarn2to3/fixes/ py3kwarn2to3/pgen2/

after_success:
    - pip install --quiet coveralls
    - coverage run --branch --omit='*/py3kwarn2to3/*,*/site-packages/*,*/distutils/*' setup.py --quiet test
    - coverage report --show-missing
    - coveralls
